version: '3.8'

networks:
  shared-network:
    driver: bridge

services:

  dgraph-zero:
    command: dgraph zero
    container_name: dgraph-zero
    environment:
      DGRAPH_ZERO_MY: dgraph-zero:5080
    image: dgraph/dgraph:v20.07.2
    networks:
      shared-network:
    
  dgraph-alpha:
    command: dgraph alpha --vmodule=server=3
    container_name: dgraph-alpha
    depends_on:
    - dgraph-zero
    env_file:
      - alpha.env
    image: dgraph/dgraph:v20.07.2
    networks:
      shared-network:
    ports:
    - published: 8080
      target: 8080

  travel-api:
    container_name: travel-api
    depends_on:
    - dgraph-alpha
    environment:
      TRAVEL_API_KEYS_MAPS_KEY: ''
    image: travel-api-amd64:1.0
    networks:
      shared-network:
    ports:
    - published: 3000 # API
      target: 3000
    - published: 4000 # DEBUG API
      target: 4000

  travel-ui:
    container_name: travel-ui
    depends_on:
    - dgraph-alpha
    environment:
      TRAVEL_API_KEYS_MAPS_KEY: ''
      TRAVEL_WEB_UI_HOST: '0.0.0.0:3080'
    image: travel-ui-amd64:1.0
    networks:
      shared-network:
    ports:
    - published: 3080 # UI
      target: 3080
    - published: 4080 # DEBUG UI
      target: 4080
